export const practiceData = {
  Mon: { target: 'K, G', hindi: 'K-Varga (क वर्ग)', articulator: 'Back of tongue to soft palate.', contact: 'Lazy tongue, continuous sigh. Barely tap the throat.', texts: ['King Kevin kept the crazy kangaroos in the grand green garden. Good girls gather golden grapes to give the great gorillas. Gary grabbed the cold cup of coffee.', 'Kites flew high over the green hills of Kathmandu. Keep the kite in the kingdom. Kind giants gather grapes. Great games give good gifts.', 'Keep the back of your tongue lazy and relaxed while pronouncing the K and G sounds. A continuous sigh ensures smooth speech without hard blocks.'] },
  Tue: { target: 'CH, J', hindi: 'Ch-Varga (च वर्ग)', articulator: 'Middle tongue to hard roof.', contact: 'Float gently, melt away. Do not press hard.', texts: ['Charlie chose cheap cheese for the joyful journey. Jack jumped joyfully over the giant jelly jar.', 'The cheerful children chanted in the chilly church. Choose chocolate cherries for the jolly children.', 'Judge Judy jokingly judged the jumpy jester. Jumping jaguars join the cheerful jungle jamboree.'] },
  Wed: { target: 'Hard T, D, R', hindi: 'T-Varga (ट वर्ग - Retroflex)', articulator: 'Curled tongue tip to roof.', contact: 'Soft bounce. Uncurl the tongue softly.', texts: ['The tall truck driver dropped the red drum down the dirt track. Twenty trains traveled through the dark tunnel today.', 'The dry desert dust trapped the running rabbit. Red roosters ran rapidly around the dirty tractor.', 'Try to trace the tricky tracks left by the runaway train. The dark dog dug a deep dirt trench.'] },
  Thu: { target: 'Soft T, D, N, TH', hindi: 'T-Varga (त वर्ग - Dental)', articulator: 'Tongue tip to back of front teeth.', contact: 'Feather touch. Barely graze the teeth.', texts: ['Today, the dentist told David that totally tiny details determine tooth decay. The deep, dark decay destroyed the top tier of the dentin.', "Don't touch the tender teeth. Tomorrow, they need to take two tools down to drill the top.", 'David took a deep breath, trusting the dentist to do the tough task. Tiny things take time to do.'] },
  Fri: { target: 'P, B, M', hindi: 'P-Varga (प वर्ग)', articulator: 'Both lips.', contact: 'Gently slide together, do not squeeze.', texts: ['Paul, the proud baker, prepared plenty of perfect blueberry pies. Big bears bumped by the back of the bakery, smelling the sweet butter.', "Many mothers marched past the bakery. Please put the pastries in the box, Paul's boss bellowed.", 'Buying massive piles of muffins and buns for breakfast. Put the purple paper by the pool.'] },
  Sat: { target: 'S, Z, L, W, H', hindi: 'Antastha & Ushma', articulator: 'Varies, never fully closed.', contact: 'Continuous breath/friction. No hard stops.', texts: ['Sally saw seven swans swimming swiftly south along the rushing river. The large, lazy lions rested right by the yellow yard.', 'We watched the rolling waves wash away the loose leaves. Hearing heavy helicopters hovering high above, Harry hurried home.', 'Slowly, the silver sun sank, leaving little light. Seven sleepy sheep rested safely.'] },
  Sun: { target: 'A, E, I, O, U', hindi: 'Swar (स्वर - Vowels)', articulator: 'Vocal Cords.', contact: 'Easy onsets. Dimmer switch volume increase.', texts: ['An amazing eagle ate an icy orange under the umbrella. Every evening, elephants eat apples in the open area.', 'I invited old uncles to our awesome island. Always eat extra eggs in the early autumn.', 'April is an awesome month to explore outdoor areas. Open umbrellas indicate incoming April showers.'] },
  Clusters: { target: 'Str, Pl, Tr, Bl', hindi: 'Samyukta Vyanjan (संयुक्त)', articulator: 'Complex jumps.', contact: 'Glide smoothly and slowly between positions.', texts: ['Strong brave dragons strictly block the clear blue stream. Please strictly train the clumsy class to play the trumpet.', 'Traffic trucks crashed across the plastic bridge. Bright blue blossoms bloom brightly on the branches.', 'Playful friends plan a pleasant trip to the grand plaza. Trust the brave travelers to cross the strong bridge.'] },
}
